//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Visma_Room2Meet
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;

    public partial class Building
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Building()
        {
            this.AspNetUsers = new HashSet<AspNetUser>();
            this.Rooms = new HashSet<Room>();
        }
    
        public int BuildingID { get; set; }
        [Required]
        [MaxLength(32)]
        public string BuildingCode { get; set; }
        [Required]
        [MaxLength(256)]
        public string Name { get; set; }
        [Required]
        [MaxLength(128)]
        public string Country { get; set; }
        [MaxLength(256)]
        [AllowHtml]
        public string Address { get; set; }
        [MaxLength(1024)]
        [AllowHtml]
        public string Description { get; set; }
        [MaxLength(512)]
        public string ImageUrl { get; set; }
        [Required]
        public System.TimeSpan OpenHour { get; set; }
        [Required]
        public System.TimeSpan CloseHour { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AspNetUser> AspNetUsers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Room> Rooms { get; set; }
    }
}
