//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Visma_Room2Meet
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class RoomRole
    {
        public int RoomRoleID { get; set; }
        public int RoomID { get; set; }
        public string AspNetRoleID { get; set; }
    
        public virtual AspNetRole AspNetRole { get; set; }
        public virtual Room Room { get; set; }
    }
}
